input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["topic2"]
    group_id => "logstash-group"
    auto_offset_reset => "earliest"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "entities"
    user => "elastic"
    password => "---YOUR PASSWORD---"
    ssl_enabled => true
    ssl_verification_mode => "none"
  }

  stdout { codec => rubydebug }
}



