# -*- coding: utf-8 -*-
"""MRFriendRec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugHaPylcFkYL6mznHLfbaWKaAZPtVbCk
"""

import wget
from pyspark import SparkContext
from itertools import combinations
import random

sc = SparkContext("local", "FriendRecommendation")

file = wget.download("https://an-ml.s3.us-west-1.amazonaws.com/soc-LiveJournal1Adj.txt")
data = sc.textFile(file)

#Pass in line and get the list of possible mutual friends of the form ((idA,idB), 1)
def mapFunc(line):
    parts = line.split("\t")
    userID = parts[0]

    if len(parts) == 1:
        return []

    friends = parts[1].split(",")

    results = []

    #account for existing friendships
    for f in friends:
        results.append(((userID,f), -1))

    # get mutual friend pairs
    for f1, f2 in combinations(friends, 2):
        results.append(((f1, f2), 1))
        results.append(((f2, f1), 1))

    return results

#flatten lists returned from each line to form one large mapped dataset
mapped = data.flatMap(mapFunc)

# Convert to form ((1, 2), [1, 1, 1]), ((2, 67), [1, 1, -1])
reduced = mapped.groupByKey().mapValues(list)

def filterPair(pair):
    users, counts = pair
    if -1 in counts:
        return None
    return (users[0], (users[1], sum(counts)))

filtered = reduced.map(filterPair).filter(lambda x: x is not None)
#Now have (1, (2, 3), ... (firstNum, (pairedNumber, # of mutual friends)))


grouped = filtered.groupByKey()
# Now have (1, [(2,3), (3, 4)]), ... = (user1, [(user i, # of mutual friends with user i)])

#get top 10 pairs in terms of # of mutual friends
def top10(recList):
    return sorted(recList, key = lambda x: -x[1])[:10]

recommendations = grouped.mapValues(top10)
#Have up to top 10 pairs

#Pick random 10 users
sample_users = recommendations.takeSample(False, 10)

#Print user and recommendations for the randomly sampled users.
for user, recs in sample_users:
    ids = [r[0] for r in recs]
    print(f"{user}\t{','.join(ids)}")

import sys
!{sys.executable} -m pip install wget

import sys
!{sys.executable} -m pip install pyspark

"""Now that `pyspark` is installed, let's initialize `SparkContext` in the first code cell and run the rest of the code."""